language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.18
  - DJANGO=1.9.13
  - DJANGO=1.10.8
  - DJANGO=1.11.9
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=1.7.11
    - python: 3.6
      env: DJANGO=1.7.11
    - python: 3.5
      env: DJANGO=1.8.18
    - python: 3.6
      env: DJANGO=1.8.18
    - python: 3.2
      env: DJANGO=1.9.13
    - python: 3.3
      env: DJANGO=1.9.13
    - python: 3.2
      env: DJANGO=1.10.8
    - python: 3.3
      env: DJANGO=1.10.8
    - python: 3.2
      env: DJANGO=1.11.9
    - python: 3.3
      env: DJANGO=1.11.9
after_success:
  - coveralls
