language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.7.10
  - DJANGO=1.8.7
  - DJANGO=1.9rc2
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.9rc2
    - python: 3.3
      env: DJANGO=1.9rc2
    - python: 3.5
      env: DJANGO=1.7.10
    - python: 3.5
      env: DJANGO=1.8.7