language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.9.13
  - DJANGO=1.10.8
  - DJANGO=1.11.9
  - DJANGO=2.0.2
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0.2
after_success:
  - coveralls
